### ISSUE TITLE
Specificity of the most specific complex selector in its selector list argument doesn't counts for  :nth-child() and :nth-last-child() selectors

### ISSUE THREAD

**Issue by Semigradsky** [LeaVerou/parsel#12]
See example 59 from https://www.w3.org/TR/selectors-4/#specificity-rules

> `:nth-child(even of li, .item)` has a specificity of `(0,2,0)`—like a class selector (`.item`) plus a pseudo-class—when matched against any of `<li>`, `<ul class=item>`, or `<li class=item id=foo>`.

```css
:nth-child(even of li, .item)
```
AST (in `recursive` parsing mode):
```json
{
	"type": "pseudo-class",
	"content": ":nth-child(even of li, .item)",
	"name": "nth-child",
	"argument": "even of li, .item",
	"pos": [
		0,
		29
	]
}
```
Specificity: `0,1,0`

**Comment by LeaVerou** [comment]
Yes, this syntax is not accounted for yet. It's parsed correctly due to Parsel's permissiveness, but it's not implemented in the specificity calculation.
