### ISSUE TITLE
selector returns weird symbol instead of attribute value

### ISSUE THREAD

**Issue by natarius** [LeaVerou/parsel#26]
so I have this selector here

footprint[uid="ca135f26-2b55-db63-7451-5a8effb2a19f"] > pad[uid="100a8763-0d5f-de60-23a5-00d74f3ecad7"]

and oddly it returns a § as value for the right side attribute

full response:

```
{
	"type": "complex",
	"combinator": ">",
	"left": {
		"type": "compound",
		"list": [
			{
				"type": "type",
				"content": "footprint",
				"name": "footprint",
				"pos": [
					0,
					9
				]
			},
			{
				"type": "attribute",
				"content": "[uid=\"ca135f26-2b55-db63-7451-5a8effb2a19f\"]",
				"name": "uid",
				"operator": "=",
				"value": "\"ca135f26-2b55-db63-7451-5a8effb2a19f\"",
				"pos": [
					9,
					18
				]
			}
		]
	},
	"right": {
		"type": "compound",
		"list": [
			{
				"type": "type",
				"content": "pad",
				"name": "pad",
				"pos": [
					21,
					24
				]
			},
			{
				"type": "attribute",
				"content": "[uid=\"§\"]",
				"name": "uid",
				"operator": "=",
				"value": "\"§\"",
				"pos": [
					24,
					33
				]
			}
		]
	}
}
```

**Comment by fffilo** [comment]
Same problem...

Input:

    parsel.tokenize('[data-abcde="abcde"][data-xyz="xyz"]');

Result:

    [
        {
            "type": "attribute",
            "content": "[data-abcde=\"abcde\"]",
            "name": "data-abcde",
            "operator": "=",
            "value": "\"abcde\"",
            "pos": [
                0,
                16
            ]
        },
        {
            "type": "attribute",
            "content": "[data-xyz=\"§\"]",
            "name": "data-xyz",
            "operator": "=",
            "value": "\"§\"",
            "pos": [
                16,
                30
            ]
        }
    ]

**Comment by fffilo** [comment]
It looks like this [pull request](https://github.com/LeaVerou/parsel/pull/16) solves the issue.

**Comment by brettalewis** [comment]
This issue should be solved by the PR that was merged yesterday.

**Comment by LeaVerou** [comment]
Closing then!
