### ISSUE TITLE
Add `stringify` method

### ISSUE THREAD

**Issue by mhyfritz** [LeaVerou/parsel#27]
Hi!

I would like to use Parsel to modify selectors and would need a `stringify` method for this that turns a list of tokens or AST back to a string. Any chance to get this added?

In any case, thanks for this great package!

**Comment by LeaVerou** [comment]
Agreed this would be useful, possibly as a separate module if it ends up being too long. I would definitely merge a PR for this, though it may be a while until I can get to it myself.
