### ISSUE TITLE
Parsing `*` reports it is a Type Selector

### ISSUE THREAD

**Issue by bramus** [LeaVerou/parsel#42]
Output for [parsing `*`](https://projects.verou.me/parsel/?selector=*) is this:

```json
{
	"type": "type",
	"content": "*",
	"pos": [
		0,
		1
	]
}
```

The `type` should be `universal`, as per https://www.w3.org/TR/selectors-4/#the-universal-selector

**Comment by LeaVerou** [comment]
Happy to merge a PR on this!
