### ISSUE TITLE
Parsing `*` does not include a name

### ISSUE THREAD

**Issue by bramus** [LeaVerou/parsel#43]
Output for [parsing `*`](https://projects.verou.me/parsel/?selector=*) is this:

```json
{
	"type": "type",
	"content": "*",
	"pos": [
		0,
		1
	]
}
```

Compare this to [parsing `p`](https://projects.verou.me/parsel/?selector=p) _(or any other selector)_: they contain a `name`:

```json
{
	"type": "type",
	"content": "p",
	"name": "p",
	"pos": [
		0,
		1
	]
}
```

I would have expected a `name` to also be included when parsing `*`

**Comment by LeaVerou** [comment]
The idea was that `name` is a specific tag name. But this will be a non-issue if the proposal in #42 is accepted.
