### ISSUE TITLE
Parsing `html|*` reports it is a Compound Selector

### ISSUE THREAD

**Issue by bramus** [LeaVerou/parsel#44]
Output for [parsing a namespaced `*`](https://projects.verou.me/parsel/?selector=html%7C*) is this:

```json
{
	"type": "compound",
	"list": [
		{
			"type": "type",
			"content": "html",
			"name": "html",
			"pos": [
				0,
				4
			]
		},
		"|",
		{
			"type": "type",
			"content": "*",
			"pos": [
				5,
				6
			]
		}
	]
}
```

This is incorrect. It’s simply namespaced universal selector.

Regular namespaced selectors – such as [`html|p`](https://projects.verou.me/parsel/?selector=html%7Cp) – work fine:

```json
{
	"type": "type",
	"content": "html|p",
	"namespace": "html",
	"name": "p",
	"pos": [
		0,
		6
	]
}
```

While drafting this issue, I noticed same thing happens when trying to [parse `html|`](https://projects.verou.me/parsel/?selector=html%7C). It’s also reported as Compound Selector.

**Comment by LeaVerou** [comment]
> Regular namespaced selectors – such as [`html|p`](https://projects.verou.me/parsel/?selector=html%7Cp) – work fine:
> 
> ```json
> {
> 	"type": "compound",
> 	"list": [
> 		{
> 			"type": "type",
> 			"content": "html",
> 			"name": "html",
> 			"pos": [
> 				0,
> 				4
> 			]
> 		},
> 		"|",
> 		{
> 			"type": "type",
> 			"content": "*",
> 			"pos": [
> 				5,
> 				6
> 			]
> 		}
> 	]
> }
> ```

I think you pasted the wrong code, this is what's produced (which is indeed correct):

```json
{
	"type": "type",
	"content": "html|p",
	"namespace": "html",
	"name": "p",
	"pos": [
		0,
		6
	]
}
```

**Comment by bramus** [comment]
> I think you pasted the wrong code

That was a copy-paste error on my part indeed. I have updated the original post to include the correct snippet.

**Comment by david-luna** [comment]
I think this one is already fixed in [this PR](https://github.com/LeaVerou/parsel/pull/45)

**Comment by bramus** [comment]
@david-luna Correct. Added an extra test in #46, verifying this.
