### ISSUE TITLE
List + compound selectors result in duplicated nodes

### ISSUE THREAD

**Issue by nolanlawson** [LeaVerou/parsel#7]
First off, thanks for making `parsel`! It's really impressive how much functionality can fit into [<2kB](https://bundlephobia.com/result?p=parsel-js@1.0.0).

I believe I've found a bug with list and compound selectors. Consider the selector:

    div.foo,span:focus

In `parsel`'s resulting AST, the `div.foo` gets lost, and it appears `span:focus` is duplicated twice:

![projects verou me_parsel_2](https://user-images.githubusercontent.com/283842/93141459-102c7680-f699-11ea-9e97-bf93b2685863.png)

**Comment by LeaVerou** [comment]
Oh wow, that's really bizarre. I can verify this. Thankfully, it looks like the tokens are correct, so it should be easy to fix. Thank you!
