### ISSUE TITLE
Fails to parse selector with empty ":where()"

### ISSUE THREAD

**Issue by guivr** [LeaVerou/parsel#71]
Hi! Just reporting a bug.

It's failing to parse selectors like this:
`.prose :where():not(:where([class~="not-prose"] *))`

I wonder if this is a valid selector, though... But instead of giving an error at the demo, it doesn't return anything - it's breaking something.

**Comment by LeaVerou** [comment]
Here’s a more compact testcase: https://parsel.verou.me/?selector=%3Awhere%28%29

There are two bugs here:
- Parsel throws with "Unexpected sequence () found at index 6" (you can see it in the console), which could be better (or even not throw at all, per Parsel's design principles of permissiveness)
- The Parsel demo page does not in any way indicate that you’ve hit an error, it just stops updating. 

Any thoughts, @jrandolf ?

**Comment by jrandolf** [comment]
`:where()` is not a valid selector. In general, a pseudo-class/pseudo-element with an empty arg (like `:test()`) is not valid, so this is working as expected.
